'''
@author: willg

PHY260, Homework #6

This module loads data generated by the generate_walks module.
'''

from generate_walks import local_data_dir
import numpy as np
import os

def get_newest_file_in_data_dir():
    # taken from http://ubuntuforums.org/showthread.php?t=1526010
    os.chdir( local_data_dir )
    # change into the data directory
    npz_filelist = [npz_file for npz_file in os.listdir( os.getcwd() ) if npz_file.endswith( '.npz' ) ]
    # make a list of all files and folders in the current working directory
    npz_filelist = filter( lambda x: not os.path.isdir( x ), npz_filelist )
    # get rid of folders in the list. we only want files.
    newest = max( npz_filelist, key = lambda x: os.stat( x ).st_mtime )
    # get newest file in the list
    os.chdir( '..' )
    # change back to the parent directory.
    return newest

def get_data( np_file_path ):
    data = np.load( np_file_path )
    walks = data['positions']
    return walks

npzfilename = get_newest_file_in_data_dir()
walks = get_data( os.getcwd() + '/' + local_data_dir + '/' + npzfilename )
